version: 2
jobs:
  build:
    working_directory: ~/materialize-hakyll
    docker:
      - image: fpco/stack-build

    steps:
      - checkout
      - run: echo "A first hello"
      - run: bash detect-pr.sh
      - run:
          name: detect using haskell
          command: |
            ./.circleci/script.hs
      - run: echo "test"